// diccionarios.ts
export const diccionarioSimplificacion: Record<string, string> = {
  "dificultad": "problema",
  "dificultades": "problemas",
  "complicado": "difícil",
  "complicada": "difícil",
  "complicadas": "difíciles",
  "compleja": "difícil",
  "complejas": "difíciles",
  "problema": "problema",
  "problemas": "problemas",
  "especifico": "exacto",
  "especifica": "exacta",
  "especificos": "exactos",
  "especificas": "exactas",
  "necesario": "importante",
  "necesaria": "importante",
  "necesarios": "importantes",
  "necesarias": "importantes",
  "alternativa": "opción",
  "alternativas": "opciones",
  "opcion": "opción",
  "opciones": "opciones",
  "rendimiento": "desempeño",
  "desempeño": "desempeño",
  "habilidad": "capacidad",
  "habilidades": "capacidades",
  "participar": "unirse",
  "participacion": "unión",
  "respuesta": "contestación",
  "respuestas": "contestaciones",
  "analisis": "revisión",
  "utilizacion": "uso",
  "utilizar": "usar",
  "comunicacion": "mensaje",
  "mensajes": "mensajes",
  "beneficio": "ventaja",
  "beneficios": "ventajas",
  "asistencia": "ayuda",
  "asistencias": "ayudas",
  "contexto": "situación",
  "contextos": "situaciones",
  "experimentar": "tener",
  "significado": "sentido",
  "reconocer": "identificar",
  "procesamiento": "análisis",
  "condición": "problema",
  "requiere": "necesita",
  "mejoren": "ayuden",
  "frecuente": "común",
  "adicional": "extra",
  "responder": "contestar",
  "solicitud": "pedido",
  "evaluar": "revisar",
  "relacionado": "conectado",
  "esencial": "necesario",
  "considerar": "pensar",
  "consecuencia": "resultado",
  "objetivo": "meta",
  "información": "dato",
  "comunicación": "mensaje",
  "desea": "quiere",
  "determinar": "decidir",
  "obtener": "conseguir",
  "situación": "momento",
  "indicar": "mostrar",
  "repetir": "decir otra vez",
  "identificar": "ver",
  "aproximadamente": "más o menos",
  "comenzar": "empezar",
  "finalizar": "terminar",
  "significativamente": "mucho",
  "significativa": "importante",
  "significativo": "importante",
  "significativos": "importantes",
  "significativas": "importantes",
  "suficiente": "bastante"
}

export function obtenerDiccionarioPalabrasDificiles(): Record<string, string> {
  return {
    abstracto: "concreto",
    adquisición: "compra",
    ambiguo: "poco claro",
    analogía: "comparación",
    análisis: "estudio",
    anómalo: "raro",
    antagonista: "enemigo",
    aproximadamente: "casi",
    articulación: "unión",
    asimilar: "entender",
    autónomo: "independiente",
    bilateral: "de dos lados",
    caótico: "desordenado",
    circunstancia: "situación",
    coherente: "lógico",
    compensación: "pago",
    complementario: "que completa",
    conciso: "breve",
    connotación: "significado",
    consecutivo: "seguido",
    consolidar: "unir",
    constitución: "formación",
    contemporáneo: "actual",
    contradicción: "oposición",
    controversia: "discusión",
    convencional: "tradicional",
    correlación: "relación",
    cualitativo: "de calidad",
    cuantitativo: "de cantidad",
    deducción: "conclusión",
    deficiencia: "falta",
    definitivo: "final",
    desproporcionado: "desigual",
    determinante: "decisivo",
    dialéctico: "de diálogo",
    dicotomía: "división",
    diferenciación: "distinción",
    dilema: "problema",
    discrepancia: "desacuerdo",
    discreto: "prudente",
    discriminación: "distinción",
    diseminación: "difusión",
    divergente: "diferente",
    diversificación: "variedad",
    ecléctico: "variado",
    efímero: "pasajero",
    empírico: "práctico",
    enigmático: "misterioso",
    epistemología: "teoría del conocimiento",
    equidistante: "a igual distancia",
    erróneo: "incorrecto",
    escéptico: "dudoso",
    esporádico: "ocasional",
    estereotipo: "idea fija",
    etimología: "origen de palabras",
    eufemismo: "expresión suave",
    exacerbar: "agravar",
    exégesis: "explicación",
    exhaustivo: "completo",
    extemporáneo: "fuera de tiempo",
    extrapolar: "aplicar",
    factible: "posible",
    falacia: "engaño",
    fenomenología: "estudio de fenómenos",
    fluctuación: "variación",
    fragmentación: "división",
    heterogéneo: "variado",
    hipotético: "supuesto",
    homogéneo: "uniforme",
    idiosincrasia: "carácter",
    implícito: "indirecto",
    incompatible: "opuesto",
    incongruente: "sin sentido",
    indeterminado: "indefinido",
    inferencia: "deducción",
    inherente: "propio",
    innovación: "novedad",
    intangible: "que no se puede tocar",
    integral: "completo",
    intrínseco: "esencial",
    irreversible: "sin vuelta atrás",
    jerarquía: "orden",
    jurisdicción: "autoridad",
    justificación: "explicación",
    legitimidad: "validez",
    longitudinal: "a lo largo",
    manifestación: "muestra",
    mecanismo: "sistema",
    metodología: "método",
    mitigar: "aliviar",
    modificación: "cambio",
    monolítico: "uniforme",
    morfología: "forma",
    negligencia: "descuido",
    obsoleto: "anticuado",
    paradigma: "modelo",
    paradójico: "contradictorio",
    parámetro: "medida",
    peculiaridad: "rareza",
    percepción: "idea",
    periférico: "exterior",
    permutación: "cambio",
    perpendicular: "en ángulo recto",
    persistente: "constante",
    perspectiva: "punto de vista",
    persuasión: "convencimiento",
    pertinente: "adecuado",
    plausible: "creíble",
    polarización: "división",
    postulado: "principio",
    pragmático: "práctico",
    precedente: "anterior",
    predicción: "pronóstico",
    preliminar: "previo",
    prerrogativa: "privilegio",
    presunción: "suposición",
    prevalente: "común",
    primordial: "principal",
    probabilidad: "posibilidad",
    procedimiento: "proceso",
    proliferación: "aumento",
    proporcional: "equilibrado",
    prospectivo: "futuro",
    protagonista: "personaje principal",
    protocolo: "normas",
    prototipo: "modelo",
    provisional: "temporal",
    proximidad: "cercanía",
    psicológico: "mental",
    puntual: "exacto",
    racionalización: "explicación",
    recíproco: "mutuo",
    redundante: "repetitivo",
    referencial: "de referencia",
    reflexivo: "pensativo",
    reiteración: "repetición",
    relativo: "relacionado",
    reminiscencia: "recuerdo",
    replicación: "copia",
    representativo: "típico",
    resolución: "solución",
    retrospectivo: "pasado",
    secuencial: "en orden",
    semántico: "de significado",
    significativo: "importante",
    simultáneo: "al mismo tiempo",
    sincrónico: "simultáneo",
    sinérgico: "cooperativo",
    sintético: "artificial",
    sistemático: "ordenado",
    subjetivo: "personal",
    subordinado: "inferior",
    subsecuente: "siguiente",
    sustancial: "importante",
    tangible: "real",
    taxonomía: "clasificación",
    tectónico: "estructural",
    tendencia: "inclinación",
    terminología: "vocabulario",
    teórico: "conceptual",
    tipología: "clasificación",
    tópico: "tema",
    trayectoria: "camino",
    trivial: "sin importancia",
    unilateral: "de un lado",
    utilitario: "útil",
    validación: "confirmación",
    variable: "cambiante",
    verificación: "comprobación",
    viable: "posible",
    viceversa: "al contrario",
    virtual: "casi real",
    volátil: "inestable",
    automáticamente: "por sí solo",
    consecuentemente: "por lo tanto",
    extraordinariamente: "muy",
    fundamentalmente: "básicamente",
    indiscutiblemente: "sin duda",
    paradójicamente: "de forma contradictoria",
    particularmente: "sobre todo",
    predominantemente: "principalmente",
    preferentemente: "mejor",
    preliminarmente: "antes",
    presumiblemente: "quizás",
    proporcionalmente: "en proporción",
    respectivamente: "en ese orden",
    satisfactoriamente: "bien",
    significativamente: "bastante",
    sustancialmente: "mucho",
    teóricamente: "en teoría",
    tradicionalmente: "desde siempre",
    voluntariamente: "por voluntad propia",
  }
}
